name = "QuantumBilliards"
uuid = "7c03dc60-f10f-4d5b-b776-32bcaab55394"
authors = ["Crt Lozej"]
version = "0.1.0"

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"


[compat]
Bessels = "0.2.8 - 3"
CairoMakie = "0.10"
CircularArrays = "1"
CoordinateTransformations = "0.6"
Distributions = "0.25"
FFTW = "1"
FastGaussQuadrature = "0.5"
ForwardDiff = "0.10"
GLMakie = "0.8"
IntervalArithmetic = "0.20"
Makie = "0.19"
Optim = "1"
Rotations = "1"
StaticArrays = "1"
TimerOutputs = "0.5"
julia = "1.8"
QuadGK = "2.11.0"
ProgressMeter = "1.10.2"
BenchmarkTools = "1.5.0"
CSV = "0.10.14"
PrettyTables = "2.3.2"
DataFrames = "1.6.1"
SpecialFunctions = "2.4.0"
LoggingExtras = "1.0.3"
JLD2 = "0.5.4"
LsqFit = "0.15.0"
SparseArrays = "1.12.0"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
